kafka:
  servers: localhost:29092
  topic:
    reweEmailsTopic: kafkaReweEmailsTopic
    topicGroup: kafkaReweEmailsTopicsGroup
test:
  topic: embedded-test-topic
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
emails:
  domains:
    gmail.com, yahoo.com